import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = path.join(projectRoot, "dist", "server");

const assets = await Promise.all([
  ["/", "index.html", "text/html; charset=utf-8", "no-cache"],
  ["/styles.css", "styles.css", "text/css; charset=utf-8", "public, max-age=86400, stale-while-revalidate=604800"],
  ["/app.bundle.js", "app.bundle.js", "text/javascript; charset=utf-8", "public, max-age=86400, stale-while-revalidate=604800"]
].map(async ([route, filename, contentType, cacheControl]) => ({
  route,
  contentType,
  cacheControl,
  body: await readFile(path.join(projectRoot, filename), "utf8")
})));

const serializedAssets = assets.map(({ route, contentType, cacheControl, body }) =>
  `  [${JSON.stringify(route)}, { contentType: ${JSON.stringify(contentType)}, cacheControl: ${JSON.stringify(cacheControl)}, body: ${JSON.stringify(body)} }]`
).join(",\n");

const ukStationsSource = (await readFile(path.join(projectRoot, "server", "uk-stations.js"), "utf8"))
  .replace("export const UK_STATIONS", "const UK_STATIONS");
const temperatureApiSource = (await readFile(path.join(projectRoot, "server", "temperature-api.js"), "utf8"))
  .replace(/^import \{ UK_STATIONS \} from "\.\/uk-stations\.js";\s*/m, "")
  .replace("export async function handleTemperatureRequest", "async function handleTemperatureRequest");

const worker = `/* Generated by scripts/build-sites.mjs. */
${ukStationsSource}
${temperatureApiSource}

const assets = new Map([
${serializedAssets}
]);

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const route = url.pathname === "/index.html" ? "/" : url.pathname;
    if (route === "/api/temperature-range") return handleTemperatureRequest(request, env);
    const asset = assets.get(route);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { Allow: "GET, HEAD" }
      });
    }

    if (!asset) {
      return new Response("Not found", {
        status: 404,
        headers: { "Content-Type": "text/plain; charset=utf-8" }
      });
    }

    return new Response(request.method === "HEAD" ? null : asset.body, {
      headers: {
        "Content-Type": asset.contentType,
        "Cache-Control": asset.cacheControl,
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "strict-origin-when-cross-origin"
      }
    });
  }
};
`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(path.join(outputDirectory, "index.js"), worker, "utf8");
console.log("Built dist/server/index.js for Sites");
