import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const moduleOrder = [
  "src/config.js",
  "src/settings.js",
  "src/aggregate.js",
  "src/api.js",
  "src/async.js",
  "src/export.js",
  "src/charts.js",
  "src/app.js"
];

function convertModule(source, filename) {
  const withoutImports = source.replace(/import\s*\{[\s\S]*?\}\s*from\s*["'][^"']+["'];?\s*/g, "");
  const classicSource = withoutImports.replace(
    /export\s+(?=(?:async\s+)?(?:const|let|var|function|class)\b)/g,
    ""
  );

  if (/^\s*import\s/m.test(classicSource) || /^\s*export\s+(?:\{|\*|default\b|(?:async\s+)?(?:const|let|var|function|class)\b)/m.test(classicSource)) {
    throw new Error(`Unsupported module syntax remains in ${filename}.`);
  }

  return `\n/* ${filename} */\n${classicSource.trim()}\n`;
}

const parts = await Promise.all(moduleOrder.map(async (filename) => {
  const source = await readFile(path.join(projectRoot, filename), "utf8");
  return convertModule(source, filename);
}));

const bundle = `/* Generated by scripts/build.mjs. Edit src/, then run npm run build. */
(function () {
  "use strict";
${parts.join("\n")}
})();
`;

await writeFile(path.join(projectRoot, "app.bundle.js"), bundle, "utf8");
console.log("Built app.bundle.js");
