import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = path.join(projectRoot, "dist", "server");

const assets = await Promise.all([
  ["/", "index.html", "text/html; charset=utf-8"],
  ["/styles.css", "styles.css", "text/css; charset=utf-8"],
  ["/app.bundle.js", "app.bundle.js", "text/javascript; charset=utf-8"]
].map(async ([route, filename, contentType]) => ({
  route,
  contentType,
  body: await readFile(path.join(projectRoot, filename), "utf8")
})));

const serializedAssets = assets.map(({ route, contentType, body }) =>
  `  [${JSON.stringify(route)}, { contentType: ${JSON.stringify(contentType)}, body: ${JSON.stringify(body)} }]`
).join(",\n");

const worker = `/* Generated by scripts/build-sites.mjs. */
const assets = new Map([
${serializedAssets}
]);

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const route = url.pathname === "/index.html" ? "/" : url.pathname;
    const asset = assets.get(route);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { Allow: "GET, HEAD" }
      });
    }

    if (!asset) {
      return new Response("Not found", {
        status: 404,
        headers: { "Content-Type": "text/plain; charset=utf-8" }
      });
    }

    return new Response(request.method === "HEAD" ? null : asset.body, {
      headers: {
        "Content-Type": asset.contentType,
        "Cache-Control": route === "/" ? "no-cache" : "public, max-age=3600",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "strict-origin-when-cross-origin"
      }
    });
  }
};
`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(path.join(outputDirectory, "index.js"), worker, "utf8");
console.log("Built dist/server/index.js for Sites");
